//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcWebApplication.CalcServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcServiceReference.CalcWebServiceSoap")]
    public interface CalcWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        CalcWebApplication.CalcServiceReference.HelloWorldResponse HelloWorld(CalcWebApplication.CalcServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CalcWebApplication.CalcServiceReference.HelloWorldResponse> HelloWorldAsync(CalcWebApplication.CalcServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int start, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int start, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divide", ReplyAction="*")]
        int Divide(int start, int by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divide", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivideAsync(int start, int by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        int Multiply(int start, int by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplyAsync(int start, int by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        int Subtract(int start, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubtractAsync(int start, int amount);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CalcWebApplication.CalcServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CalcWebApplication.CalcServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalcWebApplication.CalcServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CalcWebApplication.CalcServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcWebServiceSoapChannel : CalcWebApplication.CalcServiceReference.CalcWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcWebServiceSoapClient : System.ServiceModel.ClientBase<CalcWebApplication.CalcServiceReference.CalcWebServiceSoap>, CalcWebApplication.CalcServiceReference.CalcWebServiceSoap {
        
        public CalcWebServiceSoapClient() {
        }
        
        public CalcWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalcWebApplication.CalcServiceReference.HelloWorldResponse CalcWebApplication.CalcServiceReference.CalcWebServiceSoap.HelloWorld(CalcWebApplication.CalcServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CalcWebApplication.CalcServiceReference.HelloWorldRequest inValue = new CalcWebApplication.CalcServiceReference.HelloWorldRequest();
            inValue.Body = new CalcWebApplication.CalcServiceReference.HelloWorldRequestBody();
            CalcWebApplication.CalcServiceReference.HelloWorldResponse retVal = ((CalcWebApplication.CalcServiceReference.CalcWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalcWebApplication.CalcServiceReference.HelloWorldResponse> CalcWebApplication.CalcServiceReference.CalcWebServiceSoap.HelloWorldAsync(CalcWebApplication.CalcServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalcWebApplication.CalcServiceReference.HelloWorldResponse> HelloWorldAsync() {
            CalcWebApplication.CalcServiceReference.HelloWorldRequest inValue = new CalcWebApplication.CalcServiceReference.HelloWorldRequest();
            inValue.Body = new CalcWebApplication.CalcServiceReference.HelloWorldRequestBody();
            return ((CalcWebApplication.CalcServiceReference.CalcWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int start, int amount) {
            return base.Channel.Add(start, amount);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int start, int amount) {
            return base.Channel.AddAsync(start, amount);
        }
        
        public int Divide(int start, int by) {
            return base.Channel.Divide(start, by);
        }
        
        public System.Threading.Tasks.Task<int> DivideAsync(int start, int by) {
            return base.Channel.DivideAsync(start, by);
        }
        
        public int Multiply(int start, int by) {
            return base.Channel.Multiply(start, by);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyAsync(int start, int by) {
            return base.Channel.MultiplyAsync(start, by);
        }
        
        public int Subtract(int start, int amount) {
            return base.Channel.Subtract(start, amount);
        }
        
        public System.Threading.Tasks.Task<int> SubtractAsync(int start, int amount) {
            return base.Channel.SubtractAsync(start, amount);
        }
    }
}
